language: swift
osx_image: xcode11
before_script:
  - pod repo update
script:
  - pod lib lint --fail-fast --verbose
notifications:
  email:
    recipients:
      - israel.berezin@kaltura.com
      - noam.tamim@kaltura.com
    on_success: change
    on_failure: always
